name: serial
description: null
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.0-262.3.beta <4.0.0'

dependencies:
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  open_file: ^3.3.2
  path_provider: ^2.1.3
  pdf: ^3.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons:

flutter:
  uses-material-design: true

flutter_launcher_icons:
  ios: true
  image_path: "assets/icon.png"